# Assignment

Import numpy as np

In [1]:
#importing numpy in short as 'np'

import numpy as np

#creating a list 'a'

a = [1,2,3,4,5]

Make a python list => \[1,2,3,4,5\]

Convert it into numpy array and print it

In [2]:
#converting the list 'a' to array format using numpy.array and printing it

b = np.array(a)
b

array([1, 2, 3, 4, 5])

Make a python matrix (3 x 3) => \[[1,2,3],[4,5,6],[7,8,9]\]

Convert it into numpy array and print it

In [3]:
#Creating a matrix of (3x3)

matrix = [[1,2,3],[4,5,6],[7,8,9]]

#Converting the matrix into the numpy array and printing it
c = np.array(matrix)
c

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Make a matrix (3 x 3) using built-in methods (like arange(), reshape() etc.):

\[ [1,3,5],

 [7,9,11],
 
 [13,15,17] \]

In [4]:
#taking the values using the arange() method from 1 to 18 with a step of 2 between them
#using the reshape method to print the elements got from arange method into 3x3 array

d = np.arange(1,18,2).reshape(3,3)
d

array([[ 1,  3,  5],
       [ 7,  9, 11],
       [13, 15, 17]])

Create a numpy array with 10 random numbers from 0 to 10 (there should be few numbers greater than 1)

In [5]:
#creating a numpy array with 10 random numbers from 0 to 10

np.random.randint(low = 0, high = 10, size = 10)

array([1, 4, 6, 8, 1, 0, 8, 0, 7, 8])

In [6]:
#OR

In [7]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Create numpy array => \[1,2,3,4,5\] and convert it to 2D array with 5 rows

In [8]:
#creating a numpy array [1,2,3,4,5]
arr = np.array([1,2,3,4,5])

#using the reshape method to reshape the current 'arr' to 5 rows
arr.reshape(5,1)

array([[1],
       [2],
       [3],
       [4],
       [5]])

Print the shape of the above created array

In [9]:
#printing the shape of the above created array (arr)

arr.shape

(5,)

Create a numpy array with 10 elements in it. Access and print its 3rd, 4th and 9th element.

In [10]:
#creating a numpy array with 10 elements in it with the random method.

arr1 = np.random.randint(low = 0, high = 9, size = 10)
arr1

array([2, 7, 1, 2, 2, 2, 2, 0, 2, 1])

In [11]:
#accessing the 3rd, 4th and 9th element in the array

a1 = arr1[2]
a2 = arr[3]
a3 = arr1[8]
print(a1)
print(a2)
print(a3)

1
4
2


Print alternate elements of that array

In [12]:
#printing the alternate elements of that array (arr1)

arr1[::2]

array([2, 1, 2, 2, 2])

Change last 3 elements into 100 using broadcasting and print

In [13]:
#changing the last 3 elements to 100 using broadcast and printing it

arr1[-3:] = 100
arr1

array([  2,   7,   1,   2,   2,   2,   2, 100, 100, 100])

Create a 5 x 5 matrix (fill it with any element you like), print it.

Then print the middle (3 x 3) matrix.

In [14]:
#creating a matrix of size 25 and filling it with the random values
#using the reshape option to convert the given matrix to 5x5

arr2 = np.random.randint(low = 1, high = 25, size = 25).reshape(5,5)
arr2

array([[11, 10, 11,  9, 17],
       [ 8,  2, 17, 24, 20],
       [ 8, 11, 11, 18, 17],
       [19, 10, 21,  3, 17],
       [14,  1, 23, 24,  6]])

In [15]:
#printing the middle 3x3 matrix using the slicing method

arr2[1:4,1:4]

array([[ 2, 17, 24],
       [11, 11, 18],
       [10, 21,  3]])